package resources

var ERROR_CODE_DEVICE_MSG_ID string = "TEJAM0402"
var ERROR_CODE_PHONE_NO string = "TEJAM0403"
var ERROR_CODE_TEXT string = "TEJAM0404"
var ERROR_CODE_DATE_TIME string = "TEJAM0405"
var ERROR_CODE_MSG_TYPE string = "TEJAM0406"
var ERROR_CODE_OPERATION string = "TEJAM0407"

var INVALID_JSON_OBJECT = "TEJAM0408"
var ERROR_MSG_HEADER_MISSING = "TEJAM0409"
var CASSANDRA_SERVER_ERROR = "TEJAM0401"
var ERROR_CODE_ALL_INVALID_MESSAGES = "TEJAM0413"