package resources

var ERROR_CODE_DEVICE_MSG_ID string = "TEJAM0402"
var ERROR_CODE_PHONE_NO string = "TEJAM0403"
var ERROR_CODE_TEXT string = "TEJAM0404"
var ERROR_CODE_DATE_TIME string = "TEJAM0406"
var ERROR_CODE_MSG_TYPE string = "TEJAM0407"
var ERROR_CODE_OPERATION string = "TEJAM0409"
